# _config.yml

# Set the base path for your site.

baseurl: "/saappi"
# You might add other Jekyll configurations here later if needed.
# For example:
# title: My Awesome Site
# description: A description of my site.
