name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger the workflow on push events to the main branch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write # Allow writing repository contents (needed to push to gh-pages)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4 # Checks out your repository under $GITHUB_WORKSPACE

      # --------------------------------------------------------------- #
      #           ⬇️ ADD YOUR BUILD STEPS HERE ⬇️                      #
      #                                                                 #
      #   Replace this section with the commands needed to build your   #
      #   site. Examples below. If you only have static HTML/CSS/JS     #
      #   in main that you want copied, you might not need build steps. #
      # --------------------------------------------------------------- #

      # Example: Node.js build (like React, Vue, Svelte, etc.)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Specify your Node.js version
      - name: Install Dependencies
        run: npm install # Or yarn install, pnpm install
      - name: Build Site
        run: npm run build # Or your build script

      # Example: Jekyll build (if you need more control than default GH Pages build)
      # - name: Setup Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: '3.1' # Specify your Ruby version
      #     bundler-cache: true # Runs bundle install and caches gems
      # - name: Build Site
      #   run: bundle exec jekyll build --destination ./_site # Output to _site folder

      # Example: Hugo build
      # - name: Setup Hugo
      #   uses: peaceiris/actions-hugo@v2
      #   with:
      #     hugo-version: 'latest'
      # - name: Build Site
      #   run: hugo --destination ./public # Output to public folder

      # If NO build step needed (just copy files from main):
      # - name: No build required
      #  run: echo "Skipping build step"

      # --------------------------------------------------------------- #
      #           ⬆️ END OF BUILD STEPS ⬆️                               #
      # --------------------------------------------------------------- #

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v4 # Popular action for this
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Provided by GitHub Actions
          publish_branch: gh-pages # The branch to deploy to
          # 👇 IMPORTANT: Specify the directory containing your BUILT website files
          publish_dir: ./build # CHANGE THIS: e.g., ./dist, ./build, ./public, ./_site
          # Optional: Use if your build output is in the root or you didn't build

          # Optional: uncomment if you want clean history on gh-pages branch
          # force_orphan: true

          # Optional: uncomment if you use a custom domain
          # cname: your.custom.domain.com
